server:
  port: ${port:8761}

zuul:
  ribbon: 
   eureka: 
    enabled: true 
  routes: 
   discovery: 
    path: /discovery/**
    url: http://localhost:${server.port}

spring:
  application:
    name: zuureka-api-gateway 
  boot: 
   admin: 
    routes: 
     endpoints: env,metrics,trace,jolokia,info,configprops,logfile,refresh,flyway,liquibase,auditevents,hystrix.stream
    
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  dashboard: 
    path: home

management.security.enabled: false

endpoints: 
 hypermedia: 
  enabled: true
  
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
  path: logs/${spring.application.name}_${server.port}
