server:
  port: ${port:8761}

zuul:
  ribbon: 
   eureka: 
    enabled: true 
  routes: 
   discovery: 
    path: /discovery/**
    url: http://localhost:${server.port}

spring:
  application:
    name: zuureka-api-gateway
  jackson: 
   serialization: 
    INDENT_OUTPUT: true

#endpoints.enabled: false
endpoints.hypermedia.enabled: true
endpoints.info.enabled: true
endpoints.health.enabled: true
endpoints.env.enabled: true
endpoints.logfile.enabled: true
endpoints.auditevents.enabled: true
endpoints.metrics.enabled: true
endpoints.trace.enabled: true
endpoints.dump.enabled: false
endpoints.heapdump.enabled: false
endpoints.refresh.enabled: false
endpoints.service-registry.enabled: false
endpoints.archaius.enabled: false
endpoints.resume.enabled: false
endpoints.mappings.enabled: false
endpoints.loggers.enabled: false
endpoints.beans.enabled: false
endpoints.pause.enabled: false
endpoints.restart.enabled: false
endpoints.routes.enabled: false
endpoints.autoconfig.enabled: false
endpoints.features.enabled: false


    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  dashboard: 
    path: home

management.security.enabled: false   

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
  path: logs/${spring.application.name}_${server.port}
