eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: false    
    serviceUrl:
      defaultZone: ${eureka-url:http://localhost:8761/eureka/}
 
endpoints.hypermedia.enabled: true
endpoints.info.enabled: true
endpoints.health.enabled: true
endpoints.env.enabled: true
endpoints.logfile.enabled: true
endpoints.auditevents.enabled: true
endpoints.metrics.enabled: true
endpoints.trace.enabled: true
endpoints.dump.enabled: false
endpoints.heapdump.enabled: false
endpoints.refresh.enabled: false
endpoints.service-registry.enabled: false
endpoints.archaius.enabled: false
endpoints.resume.enabled: false
endpoints.mappings.enabled: false
endpoints.loggers.enabled: false
endpoints.beans.enabled: false
endpoints.pause.enabled: false
endpoints.restart.enabled: false
endpoints.routes.enabled: false
endpoints.autoconfig.enabled: false
endpoints.features.enabled: false
endpoints.configprops.enabled: false
endpoints.self.enabled: false
     
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
  path: logs/${spring.application.name}_${server.port}
  
management.security.enabled: false